git_org: UFTQA
git_repo: uft.automation

git_tags:

git_branches:
  master:
    push:
      jenkins:
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/UFTAutomation.Build.Launcher/buildWithParameters'
        job_parameters:
          token: UFTQABUILDTOKEN
          Branch:
            runtime: _branch_name_
          CommitHash_Before:
            runtime: _commit_hash_before_
          CommitHash_After:
            runtime: _commit_hash_after_

  UFT_12_54_SP_Patches:
    push:
      jenkins:
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/UFTAutomation.Build.Launcher/buildWithParameters'
        job_parameters:
          token: UFTQABUILDTOKEN
          Branch:
            runtime: _branch_name_
          CommitHash_Before:
            runtime: _commit_hash_before_
          CommitHash_After:
            runtime: _commit_hash_after_

  UFT_14_03_SP_Patches:
    push:
      jenkins:
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/UFTAutomation.Build.Launcher/buildWithParameters'
        job_parameters:
          token: UFTQABUILDTOKEN
          Branch:
            runtime: _branch_name_
          CommitHash_Before:
            runtime: _commit_hash_before_
          CommitHash_After:
            runtime: _commit_hash_after_
