git_org: UFTQA
git_repo: uft.automation

git_tags:

git_branches:
  master:
    push:
      jenkins:
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/UFTAutomation.Build.Launcher/buildWithParameters'
        job_parameters:
          token: UFTQABUILDTOKEN
          Branch: master

  UFT_12_54_SP_Patches:
    push:
      jenkins:
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/UFTAutomation.Build.Launcher/buildWithParameters'
        job_parameters:
          token: UFTQABUILDTOKEN
          Branch: UFT_12_54_SP_Patches

  UFT_14_03_SP_Patches:
    push:
      jenkins:
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/UFTAutomation.Build.Launcher/buildWithParameters'
        job_parameters:
          token: UFTQABUILDTOKEN
          Branch: UFT_14_03_SP_Patches
