git_org: Performance-Engineering
git_repo: UTT

git_tags:

git_branches:
  UFT_14_02: &jenkins_action_branch_default
    push:
      jenkins: &jenkins_action_default
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/UTT.Build.Launcher/buildWithParameters'
        job_parameters: &jenkins_action_params_default
          token: UFTBUILDTOKEN
          Branch:
            runtime: _branch_name_

  UFT_14_03_SP_Patches: *jenkins_action_branch_default
  UFT_14_53: *jenkins_action_branch_default
  
