git_org: Performance-Engineering
git_repo: UTT

git_tags:

git_branches:
  master: &jenkins_action_branch_default
    push:
      jenkins: &jenkins_action_default
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/UTT.Build.Launcher/buildWithParameters'
        job_parameters: &jenkins_action_params_default
          token: UFTQABUILDTOKEN
          Branch:
            runtime: _branch_name_


