commands:
- command:
  - opengrok-mirror
  - -c
  - /opengrok/etc/mirror-config.yml
  - -U
  - 'http://localhost:8080/source'
- command:
  - opengrok-reindex-project
  - '-J=-XX:-UseGCOverheadLimit'
  - -J=-Xmx16g
  - -J=-server
  - --jar
  - '/opengrok/dist/lib/opengrok.jar'
  - -t
  - '/opengrok/etc/logging.properties.template'
  - -p
  - '%PROJ%'
  - -d
  - '/opengrok/log/%PROJECT%'
  - -P
  - '%PROJECT%'
  - -U
  - 'http://localhost:8080/source'
  - --
  - --renamedHistory
  - 'on'
  - -r
  - dirbased
  - -G
  - -m
  - '256'
  - -c
  - '/usr/local/bin/ctags'
  - -U
  - 'http://localhost:8080/source'
  - -H
  - '%PROJECT%'
  env:
    LC_ALL: 'en_US.UTF-8'
  limits:
    RLIMIT_NOFILE: 1024

