// Jenkisfile (Declarative Pipeline)

// Global Variable

pipeline {
    agent {
        node {
            label 'deploy_py'
        }
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        timestamps()
    }

    parameters {
        string(name: "BRANCH", defaultValue: "master", description: "")
        string(name: "VM_NAME", defaultValue: "", description: "Name of the VM. Enter the vm name without domaain. </b>For Example:</b> Machine host is 'myd-hvm01120.hpeswlab.net' so the VM_NAME will be 'myd-hvm01120'")
        choice(name: "MODE", choices: [ "resnapshot", "uninstall"], description: "Restart: Restart the machine. \n Revert: Revert to snapshot and restart the machine.")
        string(name: "LABEL", defaultValue: "UFT_2022_0", description: "The label name is used to read the xml file. ")
        string(name: "BUILD_VERSION", defaultValue: "2022.0.0.24", description: "The label name is used to read the xml file. ")
        // string(name: "", defaultValue: "", description: "")
    }

    environment {
        VM_NAME = ${params.VM_NAME}
        MODE = ${params.MODE}
        LABEL = ${params.LABEL}
        BUILD_VERSION = ${params.BUILD_VERSION}
    }

    stages {
        stage("Prepare python virtual env"){
            steps {
                bat """
cd deployment\\pyDeployScript
D:\\UFT_Tools\\Python3.7.1_32\\python.exe -m venv venv
call venv\\Scripts\\activate.bat
python -m pip install --upgrade pip
python -m pip install -r requirements.txt
"""
            }

        }
        stage("Uninstall UFT"){
            when {
                expression {
                    params.MODE == "uninstall"
                }
            }
            steps {
                bat """
cd deployment\\pyDeployScript
python jenkins_script\\uinstall_uft.py
"""
            }
        }

        stage("Uninstall UFT"){
            when {
                expression {
                    params.MODE == "resnapshot"
                }
            }
            steps {
                bat """
cd deployment\\pyDeployScript
python jenkins_script\\resnapshot.py
"""
            }
        }

        stage("Executing Action") {
            steps {
      bat """python jenkins_script\\DeployAppTest.py"""
           }
        }
    }
}