git_org: uft
git_repo: iba

git_tags:

git_branches:
    master:
        push:
            jenkins: &jenkins_action_build_default
                enabled: true
                job_url: 'http://10.168.86.44:8080/job/IBA.Build.Launcher/buildWithParameters'
                job_parameters: &jenkins_action_params_default
                    token: UFTBUILDTOKEN
                    Branch:
                        runtime: _branch_name_
    
    

                    