git_org: uft
git_repo: qtp.addins.winbased

git_tags:

git_branches:
  master:
    push:
      jenkins: &jenkins_action_build_default
        enabled: true
        job_url: 'http://mydtbld0211.swinfra.net:8080/job/Delphi.Agents.Build/buildWithParameters'
        job_parameters: &jenkins_action_params_default
          token: UFTBUILDTOKEN
          Branch:
            runtime: _branch_name_

  UFT_14_51_Release: *jenkins_action_build_default
  UFT_14_52_Release: *jenkins_action_build_default
  UFT_14_53_Release: *jenkins_action_build_default
  UFT_14_53_SP_Patches: *jenkins_action_build_default
  
  
