git_org: uft
git_repo: sprinter

git_tags:

git_branches:
  master:
    push:
      jenkins: &jenkins_action_build_default
        enabled: true
        job_url: 'http://mydtbld0211.swinfra.net:8080/job/Sprinter.Build.Launcher/buildWithParameters'
        job_parameters: &jenkins_action_params_default
          token: UFTBUILDTOKEN
          Type: CI
          Branch:
            runtime: _branch_name_

  Sprinter_14_50_Release:
    push:
      jenkins: *jenkins_action_build_default

