git_org: uft
git_repo: st

git_tags:

git_branches:
  UFT_14_50_Release:
    push:
      jenkins:
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/ST.14.50.Build.Launcher/build'
        job_parameters: 
          token: UFTBUILDTOKEN

  master:
    push:
      jenkins: &jenkins_action_push_buildwithparam_default
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/ST.Build.Launcher/buildWithParameters'
        job_parameters:
          token: UFTBUILDTOKEN
          Branch:
            runtime: _branch_name_

    pull_request:
      opened:
        jenkins: &jenkins_action_pull_request_compile_only
          enabled: true
          job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/ST.CompileOnlyBuild.Launcher/buildWithParameters'
          job_parameters: &jenkins_action_pull_request_params_default
            token: ST_COMIPLEONLY_TOKEN
            Git_Repo_Clone_Url:
              runtime: _head_repo_clone_url_
            Head_Branch:
              runtime: _head_branch_
            Head_sha:
              runtime: _head_sha_
            Base_Branch:
              runtime: _base_branch_
            Git_PullRequest_ID:
              runtime: _pull_request_id_
      reopened:
        jenkins: *jenkins_action_pull_request_compile_only
      synchronize:
        jenkins: *jenkins_action_pull_request_compile_only

  UFT_14_03_SP_Patches:
    push:
      jenkins: *jenkins_action_push_buildwithparam_default

  UFT_12_54_SP_Patches:
    push:
      jenkins: *jenkins_action_push_buildwithparam_default
  
