git_org: uft
git_repo: st

git_tags:

git_branches:
  master:
    push:
      jenkins: &jenkins_action_build_default
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/ST.14.50.Build.Launcher/build'
        job_parameters: &jenkins_action_params_default
          token: UFTBUILDTOKEN

  UFT_12_54_SP_Patches: &jenkins_action_branch_default
    push:
      jenkins: &jenkins_action_buildwithparam_default
        <<: *jenkins_action_build_default
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/ST.Build.Launcher/buildWithParameters'
        job_parameters:
          <<: *jenkins_action_params_default
          Branch:
            runtime: _branch_name_

  UFT_14_03_SP_Patches: *jenkins_action_branch_default
  14_50/dev/rebranding: *jenkins_action_branch_default
