git_org: uft
git_repo: st

git_tags:

git_branches:
  master:
    push:
      jenkins: &jenkins_action_push_default
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/ST.14.50.Build.Launcher/build'
        job_parameters: &jenkins_action_push_params_default
          token: UFTBUILDTOKEN

    pull_request:
      opened:
        jenkins: &jenkins_action_pull_request_compile_only
          enabled: true
          job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/ST.CompileOnlyBuild.Launcher/buildWithParameters'
          job_parameters: &jenkins_action_pull_request_params_default
            token: ST_COMIPLEONLY_TOKEN
            Git_Repo_Clone_Url:
              runtime: _head_repo_clone_url_
            Head_Branch:
              runtime: _head_branch_
            Head_sha:
              runtime: _head_sha_
            Base_Branch:
              runtime: _base_branch_
            Git_PullRequest_ID:
              runtime: _pull_request_id_
      reopened:
        jenkins: *jenkins_action_pull_request_compile_only
      synchronize:
        jenkins: *jenkins_action_pull_request_compile_only


  UFT_12_54_SP_Patches: &jenkins_action_branch_default
    push:
      jenkins: &jenkins_action_push_buildwithparam_default
        <<: *jenkins_action_push_default
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/ST.Build.Launcher/buildWithParameters'
        job_parameters:
          <<: *jenkins_action_push_params_default
          Branch:
            runtime: _branch_name_

  UFT_14_03_SP_Patches: *jenkins_action_branch_default
  14_50/dev/rebranding: *jenkins_action_branch_default
