git_org: uft
git_repo: uft.demo.play

git_tags:

git_branches:
  master:
    pull_request:
      opened:
        robots:
          notes_writter:
            enabled: true
            body: |
              The compile-only builds (both Debug and Release) will be run in several minutes automatically.

              If the builds are not started in 10 minutes, please trigger the builds manually by clicking <a href="${jenkins_build_url}">this link</a>.

              Once clicked, the current page will be redirected to a blank page. This behavior is expected and just go back to the previous page.
            placeholders:
              jenkins_build_url:
                URI_BUILDER:
                  schema: http
                  host: mydtbld0211.swinfra.net:8080
                  base_uri: /job/solever.test.1/buildWithParameters
                  query:
                    token: TEST_TOKEN
                    Git_Repo_Clone_Url:
                      runtime: _head_repo_clone_url_
                    Head_Branch:
                      runtime: _head_branch_
                    Head_sha:
                      runtime: _head_sha_
                    Base_Branch:
                      runtime: _base_branch_
                    Git_PullRequest_ID:
                      runtime: _pull_request_id_
