---
- name: Launch jenkins nodes
  hosts: "{{ host_name }}"
  gather_facts: yes 
  roles:
     - launch_jenkin_node
  vars:
     service_name: "jenkinsslave-E__Jenkins2"
     display_name: "Jenkins agent (jenkinsslave-E__Jenkins2)"
     path: "C:\\Jenkins\\jenkins-slave.exe"
     debug: false