git_org: ftdevops
git_repo: samples.core

git_tags:

git_branches:
  master:
    push:
      jenkins:
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/Samples.Core.Build.Launcher/buildWithParameters'
        job_parameters:
          token: SAMPLETOKEN
          Branch: master

  Br_ABC:
    push:
      jenkins:
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/Samples.Core.Build.Launcher/buildWithParameters'
        job_parameters:
          token: SAMPLETOKEN
          Branch: Br_ABC
