git_org: ftdevops
git_repo: samples.core

git_tags:

git_branches:
  master:
    push:
      jenkins:
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/Samples.Core.Build.Launcher/buildWithParameters'
        job_parameters:
          token: SAMPLETOKEN
          Branch:
            runtime: _branch_name_
          CommitHash_Before:
            runtime: _commit_hash_before_
          CommitHash_After:
            runtime: _commit_hash_after_


  Br_ABC:
    push:
      jenkins:
        enabled: true
        job_url: 'http://mydtbld0120.hpeswlab.net:8080/job/Samples.Core.Build.Launcher/buildWithParameters'
        job_parameters:
          token: SAMPLETOKEN
          Branch:
            runtime: _branch_name_
          CommitHash_Before:
            runtime: _commit_hash_before_
          CommitHash_After:
            runtime: _commit_hash_after_
