git_org: ftdevops
git_repo: samples.core

git_tags:

git_branches:
  master:
    push:
      jenkins: &jenkins_action_default
        enabled: true
        job_url: 'http://10.168.86.8:8080/job/Samples.Core.Build.Launcher/buildWithParameters'
        job_parameters: &jenkins_action_params_default
          token: SAMPLETOKEN
          Branch:
            runtime: _branch_name_
          CommitHash_Before:
            runtime: _commit_hash_before_
          CommitHash_After:
            runtime: _commit_hash_after_

  Br_ABC:
    push:
      jenkins: 
        <<: *jenkins_action_default
        enabled: true